# Generated by Django 2.2.10 on 2020-04-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_areainfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInof',
            new_name='BookInfo',
        ),
    ]
